name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic FastAPI test
      run: |
        echo "from fastapi.testclient import TestClient\nfrom main import app\nclient = TestClient(app)\nresponse = client.get('/')\nassert response.status_code == 200" > test_temp.py
        python test_temp.py
