name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic FastAPI test
      run: |
        echo "from fastapi.testclient import TestClient" > test_temp.py
        echo "from main import app" >> test_temp.py
        echo "client = TestClient(app)" >> test_temp.py
        echo "response = client.get('/')" >> test_temp.py
        echo "assert response.status_code == 200" >> test_temp.py
        python test_temp.py
